---
name: "build images"

on: [push, pull_request]

jobs:
  docker-build:
    strategy:
      matrix:
        BASE_IMG_TAG: [
          pytorch-docker-cpu:pytorch-2.0.0-torchvision-0.15.1-torchaudio-2.0.1
          ]

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set REPO_NAME_LC
        run: echo "REPO_NAME_LC=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set ON_MAIN_BRANCH
        run: echo "ON_MAIN_BRANCH=$([ "$GITHUB_REF_NAME" == "main" ] &&  echo true || echo false)" >> $GITHUB_ENV  # If it is from the main fork and is main branch

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: env.ON_MAIN_BRANCH == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            BASE_IMG_NAME=ghcr.io/walkerlab/pytorch-docker-cpu:${{ matrix.BASE_IMG_TAG }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ env.ON_MAIN_BRANCH == 'true' }}
          tags: ghcr.io/${{ env.REPO_NAME_LC }}:${{ matrix.BASE_IMG_TAG }}